name: Terraform Apply

on:
  workflow_dispatch:

jobs:
  Terraform-apply:
    name: Terraform apply
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      # - name: Only run apply if branch is main and apply
      #   run: |
      #     if [[ "${{ github.ref }}" != "refs/heads/main" ]]; then
      #       echo "Branch is not main, exiting."
      #       exit 1
      #     fi

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          
      - name: Dev Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Dev Init Terraform
        run: terraform init -backend-config=terraform/environments/developement/backend-dev.conf

      - name: Dev Terraform Plan
        run: terraform plan -var-file=terraform/environments/developement/backend-dev.conf

      - name: Dev Terraform Apply
        run: terraform plan -auto-approve -var-file=terraform/environments/developement/backend-dev.conf
